export const pglocation = [
  {
    city: "Noida",
    pg_location: [
      { list: "Sector 12" },
      { list: "Sector 15" },
      { list: "Sector 16" },
      { list: "Sector 18" },
      { list: "Sector 22" },
      { list: "Sector 27" },
      { list: "Sector 45" },
      { list: "Sector 46" },
      { list: "Sector 61" },
      { list: "Sector 137" },
    ],
  },
  {
    city: "Delhi NCR",
    pg_location: [
      { list: "New Delhi" },
      { list: "Rajouri Garden" },
      { list: " Punjabi Bagh" },
      { list: "Vasant Kunj" },
      { list: "Malviya Nagar" },
      { list: "Ashok Nagar" },
      { list: " Pitampura" },
      { list: "Chhattarpur" },
      { list: "Mukherjee Nagar" },
      { list: "Paschim Vihar" },
    ],
  },
  {
    city: "Gurgaon",
    pg_location: [
      { list: "Sector 14" },
      { list: "Sector 17" },
      { list: "Sector 21" },
      { list: "Sector 22" },
      { list: "Sector 48" },
      { list: "Sector 49" },
      { list: "Sector 55" },
      { list: "Sector 56" },
      { list: "IMT Manesar" },
      { list: "DLF Cyber City" },
    ],
  },

  {
    city: "Bangalore",
    pg_location: [
      { list: "Koramangala" },
      { list: " Marathahalli" },
      { list: " BTM Layout" },
      { list: "HSR Layout" },
      { list: "Whitefield" },
      { list: " Indira Nagar" },
      { list: "Chandra Layout" },
      { list: "J. P. Nagar" },
      { list: " Jayanagar" },
      { list: " Bellandur" },
    ],
  },
  {
    city: "Mumbai",
    pg_location: [
      { list: " Andheri West" },
      { list: " Andheri East" },
      { list: " Malad West" },
      { list: "Navi Mumbai" },
      { list: " Powai" },
      { list: "Thane West" },
      { list: "Mira Road East" },
      { list: "Kharghar" },
      { list: " Kandivali East" },
      { list: " Bandra West" },
    ],
  },

  {
    city: "Chennai",
    pg_location: [
      { list: " Velachery" },
      { list: "  Madipakkam" },
      { list: "Chromepet" },
      { list: " Medavakkam" },
      { list: "Choolaimedu" },
      { list: " Porur" },
      { list: "Pallikaranai" },
      { list: "Urapakkam" },
      { list: " Valasaravakkam" },
      { list: " Thiruvanmiyur" },
    ],
  },
];
